### ISSUE TITLE
A link in the tutorial is broken.

### ISSUE THREAD

**Issue by arch-btw** [HP4k1h5/agora#14]
Hi :-)

**Describe the bug**

It's not really a bug but I just wanted to report that a certain link in the tutorial isn't working :-)

**To Reproduce**

1. Go to https://github.com/HP4k1h5/agora/blob/main/docs/TUTORIAL.md#getting-started
2. Scroll all the way down to "configuring workspaces"
3. Click on "See example configurations"
4. The link goes to https://github.com/HP4k1h5/agora/blob/main/docs/docs/example-configs
5. This link does not work.

**Expected behavior**

Instead of https://github.com/HP4k1h5/agora/blob/main/docs/docs/example-configs
I think it should be https://github.com/HP4k1h5/agora/blob/main/docs/example-configs

With one "/docs/" in the URL instead of 2 "/docs/".

**Additional context**

Thank you for your hard work!

**Comment by HP4k1h5** [comment]
Thanks for the bug report. I cannot reproduce what you're seeing. I pushed some changes that probably won't affect what you're describing, but there may have been an issue with an earlier version. Can you pull latest and check again?

**Comment by arch-btw** [comment]
Hi @HP4k1h5 , it appears to be fixed! Thank you so much and I apologize for the late response!
